---
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 The Linux Foundation <abelur@linux.com>

# Calls the github2gerrit composite action.
name: call-github2gerrit-composite-action

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
    branches:
      - master
      - main

jobs:
  call-in-g2g-workflow:
    if: false
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Call the lfit/github2gerrit composite action"
        id: gerrit-upload
        uses: lfit/github2gerrit@main
        with:
          SUBMIT_SINGLE_COMMITS: "true"
          USE_PR_AS_COMMIT: "false"
          GERRIT_SSH_PRIVKEY_G2G: ${{ secrets.GERRIT_SSH_PRIVKEY_G2G }}
          GERRIT_SSH_USER_G2G: ${{ vars.GERRIT_SSH_USER_G2G }}
          GERRIT_SSH_USER_G2G_EMAIL: ${{ vars.GERRIT_SSH_USER_G2G_EMAIL }}
          ORGANIZATION: ${{ vars.ORGANIZATION }}
